export const card = [
  {id: 1, type: 'apple', img: require('../Assets/Images/apple2.png')},
  {id: 2, type: 'apple', img: require('../Assets/Images/apple2.png')},
  {id: 3, type: 'orange', img: require('../Assets/Images/orange.png')},
  {id: 4, type: 'orange', img: require('../Assets/Images/orange.png')},
  {id: 5, type: 'cherry', img: require('../Assets/Images/cherry.png')},
  {id: 6, type: 'cherry', img: require('../Assets/Images/cherry.png')},
  {id: 7, type: 'wm', img: require('../Assets/Images/watermelon.png')},
  {id: 8, type: 'wm', img: require('../Assets/Images/watermelon.png')},
  {id: 9, type: 'banana', img: require('../Assets/Images/banana.png')},
  {id: 10, type: 'banana', img: require('../Assets/Images/banana.png')},
  {id: 11, type: 'pine', img: require('../Assets/Images/pineapple.png')},
  {id: 12, type: 'pine', img: require('../Assets/Images/pineapple.png')},
];

export const level2Cards = [
  {id: 1, type: 'apple', img: require('../Assets/Images/apple2.png')},
  {id: 2, type: 'apple', img: require('../Assets/Images/apple2.png')},
  {id: 3, type: 'orange', img: require('../Assets/Images/orange.png')},
  {id: 4, type: 'orange', img: require('../Assets/Images/orange.png')},
  {id: 5, type: 'cherry', img: require('../Assets/Images/cherry.png')},
  {id: 6, type: 'cherry', img: require('../Assets/Images/cherry.png')},
  {id: 7, type: 'wm', img: require('../Assets/Images/watermelon.png')},
  {id: 8, type: 'wm', img: require('../Assets/Images/watermelon.png')},
  {id: 9, type: 'banana', img: require('../Assets/Images/banana.png')},
  {id: 10, type: 'banana', img: require('../Assets/Images/banana.png')},
  {id: 11, type: 'pine', img: require('../Assets/Images/pineapple.png')},
  {id: 12, type: 'pine', img: require('../Assets/Images/pineapple.png')},
  {id: 13, type: 'mango', img: require('../Assets/Images/mango.png')},
  {id: 14, type: 'mango', img: require('../Assets/Images/mango.png')},
  {id: 15, type: 'pear', img: require('../Assets/Images/pear.png')},
  {id: 16, type: 'pear', img: require('../Assets/Images/pear.png')},
];

export const level3Cards = [
  {id: 1, type: 'apple', img: require('../Assets/Images/apple2.png')},
  {id: 2, type: 'apple', img: require('../Assets/Images/apple2.png')},
  {id: 3, type: 'orange', img: require('../Assets/Images/orange.png')},
  {id: 4, type: 'orange', img: require('../Assets/Images/orange.png')},
  {id: 5, type: 'cherry', img: require('../Assets/Images/cherry.png')},
  {id: 6, type: 'cherry', img: require('../Assets/Images/cherry.png')},
  {id: 7, type: 'wm', img: require('../Assets/Images/watermelon.png')},
  {id: 8, type: 'wm', img: require('../Assets/Images/watermelon.png')},
  {id: 9, type: 'banana', img: require('../Assets/Images/banana.png')},
  {id: 10, type: 'banana', img: require('../Assets/Images/banana.png')},
  {id: 11, type: 'pine', img: require('../Assets/Images/pineapple.png')},
  {id: 12, type: 'pine', img: require('../Assets/Images/pineapple.png')},
  {id: 13, type: 'mango', img: require('../Assets/Images/mango.png')},
  {id: 14, type: 'mango', img: require('../Assets/Images/mango.png')},
  {id: 15, type: 'pear', img: require('../Assets/Images/pear.png')},
  {id: 16, type: 'pear', img: require('../Assets/Images/pear.png')},
  {id: 17, type: 'grapes', img: require('../Assets/Images/grapes.png')},
  {id: 18, type: 'grapes', img: require('../Assets/Images/grapes.png')},
  {id: 19, type: 'peach', img: require('../Assets/Images/peach.png')},
  {id: 20, type: 'peach', img: require('../Assets/Images/peach.png')},
];

export const level4Cards = [
  {id: 1, type: 'apple', img: require('../Assets/Images/apple2.png')},
  {id: 2, type: 'apple', img: require('../Assets/Images/apple2.png')},
  {id: 3, type: 'orange', img: require('../Assets/Images/orange.png')},
  {id: 4, type: 'orange', img: require('../Assets/Images/orange.png')},
  {id: 5, type: 'cherry', img: require('../Assets/Images/cherry.png')},
  {id: 6, type: 'cherry', img: require('../Assets/Images/cherry.png')},
  {id: 7, type: 'wm', img: require('../Assets/Images/watermelon.png')},
  {id: 8, type: 'wm', img: require('../Assets/Images/watermelon.png')},
  {id: 9, type: 'banana', img: require('../Assets/Images/banana.png')},
  {id: 10, type: 'banana', img: require('../Assets/Images/banana.png')},
  {id: 11, type: 'pine', img: require('../Assets/Images/pineapple.png')},
  {id: 12, type: 'pine', img: require('../Assets/Images/pineapple.png')},
  {id: 13, type: 'mango', img: require('../Assets/Images/mango.png')},
  {id: 14, type: 'mango', img: require('../Assets/Images/mango.png')},
  {id: 15, type: 'pear', img: require('../Assets/Images/pear.png')},
  {id: 16, type: 'pear', img: require('../Assets/Images/pear.png')},
  {id: 17, type: 'grapes', img: require('../Assets/Images/grapes.png')},
  {id: 18, type: 'grapes', img: require('../Assets/Images/grapes.png')},
  {id: 19, type: 'peach', img: require('../Assets/Images/peach.png')},
  {id: 20, type: 'peach', img: require('../Assets/Images/peach.png')},
  {
    id: 21,
    type: 'carambola',
    img: require('../Assets/Images/carambola.png'),
  },
  {
    id: 22,
    type: 'carambola',
    img: require('../Assets/Images/carambola.png'),
  },
  {id: 23, type: 'kiwi', img: require('../Assets/Images/kiwi.png')},
  {id: 24, type: 'kiwi', img: require('../Assets/Images/kiwi.png')},
];
